// Generated by purs bundle 0.14.5
var PS = {};
(function(exports) {
  "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign.log;
})(PS);
(function(exports) {
  exports.markdownit = () => {
    const MarkdownIt = require("markdown-it");
    return new MarkdownIt();
  }

  exports.render = (app) => { return (md) => {
    return app.render(md);
  }}
})(PS["Markdownit.Markdownit"] = PS["Markdownit.Markdownit"] || {});
(function($PS) {
  "use strict";
  $PS["Markdownit.Markdownit"] = $PS["Markdownit.Markdownit"] || {};
  var exports = $PS["Markdownit.Markdownit"];
  var $foreign = $PS["Markdownit.Markdownit"];
  exports["markdownit"] = $foreign.markdownit;
  exports["render"] = $foreign.render;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Effect_Console = $PS["Effect.Console"];
  var Markdownit_Markdownit = $PS["Markdownit.Markdownit"];                
  var main = function __do() {
      var app = Markdownit_Markdownit.markdownit();
      return Effect_Console.log(Markdownit_Markdownit.render(app)("aaa"))();
  };
  exports["main"] = main;
})(PS);
PS["Main"].main();